### ISSUE TITLE
Moore's voting algorithm

### ISSUE THREAD

**Issue by stubborn-1508** [hogrider301/dsa-for-everyone#12]
I would like to add moore voting algorithm in C++.Please assign this issue to me under the label hacktoberfest.

**Comment by RishabhSharma96** [comment]
@stubborn-1508 please assign it to me.

**Comment by RishabhSharma96** [comment]
@hogrider301 please assign it to me.

**Comment by Gur-jot** [comment]
please assign this issue to me
