### ISSUE TITLE
Problems on Recursion and backtracking

### ISSUE THREAD

**Issue by niteshkumar257** [hogrider301/dsa-for-everyone#24]
1. Fibonnaci Number
2. Find all subsets of the array
3. Find all subsequene of the string
4. Combination sum 
5. All Permutaion of the string

**Comment by sandesh-3112** [comment]
please assign this to be under hacktoberfest2022 tag

**Comment by omgaydhane** [comment]
Hi @hogrider301, can you assign me this?

**Comment by aanchalsharmaa1024** [comment]
I can do it . plz assign it to me
