### ISSUE TITLE
Want to add All binary Tree problems

### ISSUE THREAD

**Issue by niteshkumar257** [hogrider301/dsa-for-everyone#31]
1. DFS
2. BFS
3. Height of the binary tree
4. Diameter of the binary tree
5. Same Tree
6. Invert Binary Tree
7. Mirror of a Binary Tree
8. Root to leaf path sum
9. Minimum time to burn the binary tree
10. Left view of binary tree
11. Right view of a binary tree
12. Boundary Traversal
13. Vertical Traversal
14. Lowest Common Ancestor in a Binary Tree
15. Zig-Zag Traversal in a Binary tree

**Comment by niteshkumar257** [comment]
please assign this to me

**Comment by Dhanshriborse** [comment]
please assign this to me.I want to work on it.

**Comment by stubborn-1508** [comment]
Please assign this issue to me.

**Comment by aanchalsharmaa1024** [comment]
plz assign it to me . I can do it .
