### ISSUE TITLE
Want to add some question on LinkedList, Please Assign to me!

### ISSUE THREAD

**Issue by siwanijaiswal** [hogrider301/dsa-for-everyone#32]
1. Remove Nth Node From End of List
2. Design HashSet
3. Maximum Twin Sum of a Linked List
4. Remove Linked List Elements
5. Remove Duplicates from Sorted List

**Comment by anirudh0806** [comment]
Please assign this to me

**Comment by deepesh16b** [comment]
Please assign this to me.

**Comment by aanchalsharmaa1024** [comment]
pls assign it to me. I can do it

**Comment by hogrider301** [comment]
Lgtm 👍
