### ISSUE TITLE
Update Readme/Documentation

### ISSUE THREAD

**Issue by Raporaz03** [hogrider301/dsa-for-everyone#43]
I will update your documentation by adding following things

1. Instructions for beginners.
2. Adding attractive images and gifs 
3. Information about project. What to do /things needed

Can I start?

**Comment by hardik302001** [comment]
Sure

**Comment by hogrider301** [comment]
Yee

**Comment by aanchalsharmaa1024** [comment]
I can do it . plz assign it to me

**Comment by Raporaz03** [comment]
ok starting now

**Comment by Raporaz03** [comment]
updated readme file

**Comment by Raporaz03** [comment]
![image](https://user-images.githubusercontent.com/73410445/194761325-bb0e3495-0c8a-4774-9cdc-ec222f288971.png)
